- name: identify installation (theme)
  shell: "wp --allow-root --no-color --path='{{ item.0.path }}' theme is-installed {{ item.1 }}"
  register: check_installation_themes
  failed_when: False
  changed_when: False
  with_subelements:
    - wordpress_installs
    - themes
  when: item.1
  tags: [configuration, wordpress, wordpress-themes, wordpress-is-installed-theme]

- name: install (theme)
  shell: "wp --allow-root --no-color --path='{{ item.item.0.path }}' theme install {{ item.item.1 }}"
  with_items: check_installation_themes.results
  when: check_installation_themes is defined and item.item.1 and item.rc != 0
  tags: [configuration, wordpress, wordpress-themes, wordpress-install-theme]

- name: check install (theme)
  shell: "wp --allow-root --no-color --path='{{ item.0.path }}' theme is-installed {{ item.1 }}"
  changed_when: False
  with_subelements:
    - wordpress_installs
    - themes
  when: item.1
  tags: [configuration, wordpress, wordpress-themes, wordpress-install-theme-check]
  
- name: update (theme)
  shell: "wp --allow-root --no-color --path='{{ item.item.0.path }}' theme update {{ item.item.1 }}"
  with_items: check_installation_themes.results
  when: check_installation_themes is defined and item.item.1 and item.rc == 0 and themes_update == 1
  tags: [configuration, wordpress, wordpress-themes, wordpress-update-theme]

