- name: install (wp-cli)
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "{{ wordpress_wp_cli_install_dir }}/wp"
    force: true
    owner: root
    group: root
    mode: 0755
#  sudo: true
#  sudo_user: root
  tags: [configuration, wordpress, wordpress-wp-cli, wordpress-wp-cli-install]
