---
- hosts: all
  vars:
    wordpress_wp_cli_install_dir: /usr/local/bin
    wordpress_dir_name: devel
    wordpress_installs:
    - name: devel
      dbname: w_devel
      dbuser: w_devel
      dbpass: 'password'
      dbhost: '127.0.0.1'
      path: "/srv/wordpress/sites/{{ wordpress_dir_name }}/root" 
      url: 'wordpress-ansible.com'
      title: 'Wordpress Ansible Page'
      admin_name: 'Del_S'
      admin_email: 'david@sucharda.cz'
      admin_password: 'Super_Silne123'
      core_update: false
      plugins_update: false
      themes_update: false
      themes: []
      plugins: ['autoptimize', 'jetpack']
  sudo: yes
  sudo_user: ansible
  tasks:
  - include: tasks/wp-cli.yml
  - include: tasks/core.yml
  - include: tasks/themes.yml
  - include: tasks/plugins.yml
